title: 'Dr Strangelet | Space Baron & Maker of Things'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.720541991526261
  brandStrength: 0.2753865148406476
  rhythmicContrast: 0.2744029874447733
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.08485283120535314
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Dr Strangelet
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2434847895056009
layout_spectrum: 0
